name: Claude State Machine
description: Run state machine to derive actions from issue state (does not execute actions)

inputs:
  mode:
    description: 'Operation mode: "derive" runs full state machine, "context" only fetches context'
    required: false
    default: "derive"
  github_token:
    description: GitHub token for API operations (read-only)
    required: true
  issue_number:
    description: Issue number to process
    required: true
  project_number:
    description: GitHub Project number
    required: true
  trigger:
    description: Event trigger type (issue_assigned, issue_edited, workflow_run_completed, pr_review_submitted, etc.)
    required: true
  ci_result:
    description: CI result (success, failure, cancelled) - required for workflow_run_completed trigger
    required: false
  ci_run_url:
    description: CI run URL - optional for workflow_run_completed trigger
    required: false
  ci_commit_sha:
    description: CI commit SHA - optional for workflow_run_completed trigger
    required: false
  review_decision:
    description: Review decision (APPROVED, CHANGES_REQUESTED, COMMENTED) - required for pr_review_submitted trigger
    required: false
  reviewer:
    description: Reviewer username - optional for pr_review_submitted trigger
    required: false
  comment_context_type:
    description: Context type (Issue or PR) - optional for issue_comment trigger
    required: false
  comment_context_description:
    description: Context description - optional for issue_comment trigger
    required: false
  branch:
    description: Branch name for the work - optional, derived from issue number if not provided
    required: false
  max_retries:
    description: Maximum number of CI failures before blocking
    required: false
    default: "5"
  bot_username:
    description: Username of the bot account
    required: false
    default: "nopo-bot"
  workflow_started_at:
    description: ISO 8601 timestamp of when the workflow started (defaults to current time)
    required: false

outputs:
  actions_json:
    description: JSON array of actions to execute (pass to claude-state-executor)
  final_state:
    description: Final state of the machine after processing
  transition_name:
    description: Human-readable name for the transition (e.g., "Iterate", "Triage", "Fix CI")
  context_json:
    description: Full machine context as JSON (for debugging)
  action_count:
    description: Number of actions derived
  iteration:
    description: Current iteration number from project field
  phase:
    description: Current phase number (or "-" if no phases)
  parent_issue_number:
    description: Parent issue number (same as issue_number if no parent)

runs:
  using: node20
  main: dist/index.cjs
