name: 'Docker Run Action'
description: 'Run a command inside a Docker container using nopo run'
inputs:
  tag:
    description: 'The tag of the image to run.'
    required: true
  service:
    description: 'The service to run'
    required: false
  run:
    description: 'Command to run inside the container (e.g., test, check)'
    required: false
  target:
    description: 'Docker target to run (development|production)'
    required: false
    default: 'production'

runs:
  using: 'composite'
  steps:
    - name: Up
      if: ${{ inputs.run == ''}}
      id: run
      shell: bash
      env:
        tag: ${{ inputs.tag }}
        target: ${{ inputs.target }}
      run: |
        make up \
          DOCKER_TAG="${tag}" \
          DOCKER_TARGET="${target}" \
          DOCKER_PORT="80"
    - name: Run
      if: ${{ inputs.run != ''}}
      shell: bash
      env:
        service: ${{ inputs.service }}
        run: ${{ inputs.run }}
        tag: ${{ inputs.tag }}
        target: ${{ inputs.target }}
      run: |
        make run ${run} ${service} \
          DOCKER_TAG="${tag}" \
          DOCKER_TARGET="${target}" \
          DOCKER_PORT="80"
