name: 'Docker Run Action'
description: 'Run a command in a new container or on the host'
inputs:
  tag:
    description: 'The tag of the image to run. If not provided, uses the default from make env.'
    required: false
  service:
    description: 'The service to run'
    required: false
  run:
    description: 'Command to run (e.g., test, check)'
    required: false
  target:
    description: 'Docker target to run (development|production)'
    required: false
    default: 'production'
  dir:
    description: 'Working directory to run commands from'
    required: false
    default: '.'

runs:
  using: 'composite'
  steps:
    - name: Up
      if: ${{ inputs.run == ''}}
      id: run
      shell: bash
      working-directory: ${{ inputs.dir }}
      env:
        tag: ${{ inputs.tag }}
        target: ${{ inputs.target }}
      run: |
        args=("DOCKER_TARGET=${target}" "DOCKER_PORT=80")
        [[ -n "$tag" ]] && args+=("DOCKER_TAG=$tag")
        make up "${args[@]}"
    - name: Run
      if: ${{ inputs.run != ''}}
      shell: bash
      working-directory: ${{ inputs.dir }}
      env:
        service: ${{ inputs.service }}
        run: ${{ inputs.run }}
        tag: ${{ inputs.tag }}
        target: ${{ inputs.target }}
      run: |
        args=("DOCKER_TARGET=${target}" "DOCKER_PORT=80")
        [[ -n "$tag" ]] && args+=("DOCKER_TAG=$tag")
        make ${run} ${service} "${args[@]}"
