name: State Machine PEV (Predict-Execute-Verify)
description: >
  Unified state machine action that runs predict-execute-verify
  in a single invocation. Prototype for the new PEV architecture.

inputs:
  github_json:
    description: Full GitHub context JSON string (pass via toJson(github) in workflow)
    required: true
  max_transitions:
    description: Maximum transitions before exiting (default 1)
    required: false
    default: "1"
  github_token:
    description: GitHub token for API operations and code changes (NOPO_BOT_PAT)
    required: true
  reviewer_token:
    description: GitHub token for PR review tasks (CLAUDE_REVIEWER_PAT). Falls back to github_token if not set.
    required: false
  project_number:
    description: GitHub Project number for reading/writing project fields (Status, Iteration, Failures)
    required: false
    default: "0"

outputs:
  final_state:
    description: Final machine state after PEV cycle
  actions_executed:
    description: Number of actions executed
  error:
    description: Error message if any

runs:
  using: node20
  main: dist/index.cjs
