primary_region = "fra"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 80
min_machines_running = 0
processes = [ "app" ]

[env]
  BACKEND_PUBLIC_URL = "https://nopo-prod-backend.fly.dev"
  WEB_PUBLIC_URL = "https://nopo-prod-web.fly.dev"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"
memory_mb = 1_024

