import compose from "docker-compose";
import {
  TargetScript,
  type ScriptDependency,
  createLogger,
} from "../lib.ts";
import EnvScript from "./env.ts";
import { baseArgs } from "../args.ts";
import type { ScriptArgs } from "../script-args.ts";

export default class PullScript extends TargetScript {
  static override name = "pull";
  static override description = "Pull the base image";
  static override dependencies: ScriptDependency[] = [
    {
      class: EnvScript,
      enabled: true,
    },
  ];

  // Define args (targets handled separately by Runner)
  static override args = baseArgs.extend({});

  // No more parseArgs - it's auto-generated by Runner

  override async fn(args: ScriptArgs) {
    const requestedTargets = args.get<string[]>("targets");

    if (requestedTargets && requestedTargets.length > 0) {
      // Pull specific target images from main compose file
      await compose.pullMany(requestedTargets, {
        callback: createLogger("pull", "blue"),
        commandOptions: ["--ignore-pull-failures"],
        env: this.env,
      });
    } else {
      // No targets specified - don't pull anything
      // Base image pulling is not needed since:
      // 1. When running locally, build script handles it
      // 2. When running in CI, only service images are pushed to registry
      this.log("No targets specified, skipping pull");
    }
  }
}
