name: Claude State Machine Entry Point
description: >
  Unified state machine entry point that detects GitHub events and routes
  to the appropriate state machine. Combines event detection and routing
  into a single action.

inputs:
  mode:
    description: |
      Operation mode:
        "detect" - detect event, compute skip/concurrency, output context_json (for sm-trigger.yml)
        "derive" - full state machine: detect event (if context_json not provided), build context, derive actions
        "context" - only fetch context (iteration, phase) without running state machine
    required: false
    default: "derive"
  github_token:
    description: GitHub token for API operations
    required: true
  project_number:
    description: GitHub Project number
    required: false
    default: "1"
  resource_number:
    description: Resource number for workflow_dispatch events
    required: false
    default: ''
  context_json:
    description: |
      Pre-built context JSON from a previous "detect" mode call.
      If not provided in "derive" or "context" mode, event detection runs automatically.
    required: false
    default: ''
  max_retries:
    description: Maximum number of CI failures before blocking
    required: false
    default: "5"
  bot_username:
    description: Username of the bot account
    required: false
    default: "nopo-bot"

outputs:
  # Detection outputs (mode: detect)
  context_json:
    description: |
      Unified JSON context containing all routing and resource information.
      In "detect" mode: detection context with skip/concurrency fields.
      In "derive"/"context" mode: full machine context as JSON.
  skip:
    description: Whether to skip processing (true/false string)
  skip_reason:
    description: Reason for skipping
  concurrency_group:
    description: Concurrency group name for workflow-level concurrency
  cancel_in_progress:
    description: Whether to cancel in-progress runs (true/false string)

  # Routing outputs (mode: derive)
  actions_json:
    description: JSON array of actions to execute (pass to executor)
  final_state:
    description: Final state of the machine after processing
  transition_name:
    description: Human-readable name for the transition (e.g., "Iterate", "Triage", "Research", "Respond")
  action_count:
    description: Number of actions derived

  # Issue-specific outputs
  iteration:
    description: Current iteration number from project field
  phase:
    description: Current phase number (or "-" if no phases)
  parent_issue_number:
    description: Parent issue number (same as issue_number if no parent)
  pr_number:
    description: PR number if a PR is associated with this issue/phase
  commit_sha:
    description: Commit SHA from CI context (if available)
  sub_issue_number:
    description: Sub-issue number if processing a phased issue
  agent_notes:
    description: Formatted agent notes from previous workflow runs (for prompt injection)

  # Discussion-specific outputs
  discussion_number:
    description: Discussion number (for discussion triggers)

runs:
  using: node20
  main: dist/index.cjs
