# actionlint configuration
# https://github.com/rhysd/actionlint/blob/main/docs/config.md

self-hosted-runner:
  labels: []

# Ignore patterns are regular expressions matching error messages
# SC2086: Double quote to prevent globbing (often intentional with GHA expressions)
# SC2016: Expressions don't expand in single quotes (intentional for literal $ in heredocs)
# SC2129: Consider using { cmd1; cmd2; } >> file (style preference)
# SC2012: Use find instead of ls (style preference)
# SC2034: Variable appears unused (false positives with GITHUB_OUTPUT)
paths:
  .github/workflows/**/*.yml:
    ignore:
      - 'shellcheck reported issue in this script: SC2086:.+'
      - 'shellcheck reported issue in this script: SC2016:.+'
      - 'shellcheck reported issue in this script: SC2129:.+'
      - 'shellcheck reported issue in this script: SC2012:.+'
      - 'shellcheck reported issue in this script: SC2034:.+'
      # TODO: Fix claude-parse-state action to match workflow usage
      # These inputs/outputs are used in workflows but not defined in action.yml
      - 'input "iteration_message" is not defined in action "Claude Project State"'
      - 'input "failure_type" is not defined in action "Claude Project State"'
      - 'property "pr_number" is not defined in object type'
      - 'property "consecutive_failures" is not defined in object type'
      # Shellcheck info/style messages that are not errors
      - 'shellcheck reported issue in this script: SC2153:.+'
      - 'shellcheck reported issue in this script: SC2002:.+'
