# Actionlint configuration
# https://github.com/rhysd/actionlint/blob/main/docs/config.md

self-hosted-runner:
  labels: []

config-variables: null

# Configuration for file paths with ignore patterns
paths:
  .github/workflows/**/*.yml:
    ignore:
      # jobs.<job_id>.result is valid in workflow outputs but actionlint's schema doesn't include it
      # https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-outputs-from-a-reusable-workflow
      - 'property "result" is not defined in object type'
      # Ignore shellcheck info and style level hints - only report warning/error
      - 'SC\d+:info:'
      - 'SC\d+:style:'
