FROM node:20-slim AS base

SHELL ["/bin/bash", "-c"]

ARG NODE_ENV

ENV HOME=/app
ENV NODE_ENV=$NODE_ENV
ENV PATH=$HOME/node_modules/.bin:$PATH

WORKDIR $HOME

FROM base AS source

COPY . $HOME

FROM base AS dependencies

COPY \
  package.json \
  package-lock.json \
  web/package.json \
  env/package.json \
  db/package.json \
  $HOME/

RUN npm ci

FROM base AS build

COPY --from=source $HOME $HOME

RUN <<EOF
NODE_ENV=development npm install
npm run build -- --filter=web
EOF

FROM base AS development

COPY --from=source $HOME $HOME

FROM dependencies AS production

COPY --from=build $HOME/web/build $HOME/web/build
COPY --from=build $HOME/db/build $HOME/db/build

CMD ["npm", "run", "start", "-w", "web"]
