FROM node:20-slim AS base

SHELL ["/bin/bash", "-c"]

ARG NODE_ENV

ENV HOME=/app
ENV NODE_ENV=$NODE_ENV
ENV PATH=$HOME/node_modules/.bin:$PATH

WORKDIR $HOME

FROM base AS source

COPY . $HOME

FROM base AS dependencies

RUN \
  --mount=type=bind,source=package.json,target=$HOME/package.json \
  --mount=type=bind,source=./web/package.json,target=$HOME/web/package.json \
  --mount=type=bind,source=package-lock.json,target=$HOME/package-lock.json \
  npm ci

FROM base AS build

COPY --from=source $HOME $HOME

RUN <<EOF
NODE_ENV=development npm install
npm run build -w web
EOF

FROM dependencies AS development

COPY --from=source $HOME $HOME
COPY --from=dependencies $HOME/web/node_modules $HOME/web/node_modules

CMD ["npm", "run", "dev", "-w", "web"]

FROM dependencies AS production

COPY package.json $HOME/package.json
COPY package-lock.json $HOME/package-lock.json
COPY --from=build $HOME/web/build $HOME/web/build

CMD ["npm", "run", "start", "-w", "web"]
