packages:
  - packages/*
  - apps/*

linkWorkspacePackages: true
preferWorkspacePackages: true

engineStrict: true
packageManagerStrict: true
nodeLinker: hoisted

onlyBuiltDependencies:
  - esbuild

storeDir: "${PNPM_STORE_DIR:-.pnpm-store}"
