packages:
  - packages/*
  - apps/*

linkWorkspacePackages: true
preferWorkspacePackages: true

engineStrict: true
packageManagerStrict: true

onlyBuiltDependencies:
  - esbuild

storeDir: "${PNPM_STORE_DIR:-.pnpm-store}"
virtualStoreDir: "${PNPM_VIRTUAL_STORE_DIR:-node_modules/.pnpm}"
