packages:
  - nopo/scripts
  - packages/*
  - apps/*
  - .github/actions-ts

linkWorkspacePackages: true
preferWorkspacePackages: true

engineStrict: true
packageManagerStrict: true

onlyBuiltDependencies:
  - esbuild

storeDir: "${PNPM_STORE_DIR:-.pnpm-store}"
