name: PR View Extended
description: Get PR details including body, author, and linked issue number

inputs:
  gh_token:
    description: GitHub token for authentication
    required: true
  head_branch:
    description: Find PR by head branch name
    required: false
  pr_number:
    description: Find PR by number
    required: false
  repository:
    description: Repository in owner/repo format (defaults to current repository)
    required: false

outputs:
  has_pr:
    description: Whether a PR was found
  is_claude_pr:
    description: Whether this is a Claude PR (author is claude[bot] or branch starts with claude/)
  is_draft:
    description: Whether the PR is a draft
  pr_number:
    description: The PR number
  pr_head_branch:
    description: The PR head branch name
  pr_body:
    description: The PR body content
  has_issue:
    description: Whether the PR body contains a linked issue
  issue_number:
    description: The linked issue number (from Fixes/Closes/Resolves #N pattern)

runs:
  using: node20
  main: dist/index.cjs
