name: Smoketest
description: Run smoke tests on a given URL

inputs:
  public_url:
    description: The public URL of the app to test
    required: true
  name:
    description: The name of the smoketest
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Install Playwright Browsers
      shell: bash
      run: pnpm exec playwright install --with-deps

    - name: Run Playwright tests
      shell: bash
      env:
        PUBLIC_URL: ${{ inputs.public_url }}
      run: |
        echo "PUBLIC_URL: ${PUBLIC_URL}"
        pnpm exec playwright test --reporter=list

    - uses: actions/upload-artifact@v4
      if: ${{ always() && inputs.name != '' }}
      with:
        name: playwright-report-${{ inputs.name }}
        path: playwright-report/
        retention-days: 30
