name: Deploy to GCP
description: Deploy services to Google Cloud Platform using Terraform (services layer)

inputs:
  project_id:
    description: The GCP project ID
    required: true
  region:
    description: The GCP region
    required: false
    default: "us-central1"
  environment:
    description: The deployment environment (stage, prod)
    required: true
  domain:
    description: The domain name
    required: true
  subdomain_prefix:
    description: The subdomain prefix (e.g., 'stage' or empty for apex)
    required: false
    default: ""
  # Stable slot images (optional - omit to skip deployment)
  stable_backend_image:
    description: Docker image for stable backend service (optional - omit to skip backend)
    required: false
    default: ""
  stable_web_image:
    description: Docker image for stable web service (optional - omit to skip web)
    required: false
    default: ""
  # Canary slot images (optional - omit to skip deployment)
  canary_backend_image:
    description: Docker image for canary backend service (optional - omit to skip backend)
    required: false
    default: ""
  canary_web_image:
    description: Docker image for canary web service (optional - omit to skip web)
    required: false
    default: ""
  terraform_state_bucket:
    description: The GCS bucket for Terraform state
    required: true

outputs:
  load_balancer_ip:
    description: The load balancer IP address
    value: ${{ steps.infra_outputs.outputs.load_balancer_ip }}
  public_url:
    description: The public URL
    value: ${{ steps.apply.outputs.public_url }}
  canary_header:
    description: Header to send for canary routing
    value: ${{ steps.apply.outputs.canary_header }}
  artifact_registry_url:
    description: The Artifact Registry URL
    value: ${{ steps.infra_outputs.outputs.artifact_registry_url }}
  static_bucket_name:
    description: The static assets bucket name
    value: ${{ steps.infra_outputs.outputs.static_bucket_name }}

runs:
  using: "composite"
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.7.0"
        terraform_wrapper: false

    # Get outputs from infra layer (for artifact registry URL, bucket name, etc.)
    - name: Get infra layer outputs
      id: infra_outputs
      shell: bash
      working-directory: infrastructure/terraform/environments/${{ inputs.environment }}/infra
      env:
        TF_STATE_BUCKET: ${{ inputs.terraform_state_bucket }}
        ENVIRONMENT: ${{ inputs.environment }}
      run: |
        terraform init -input=false \
          -backend-config="bucket=${TF_STATE_BUCKET}" \
          -backend-config="prefix=nopo/${ENVIRONMENT}/infra"

        artifact_registry_url=$(terraform output -raw artifact_registry_url 2>/dev/null || echo "")
        static_bucket_name=$(terraform output -raw static_bucket_name 2>/dev/null || echo "")
        load_balancer_ip=$(terraform output -raw load_balancer_ip 2>/dev/null || echo "")

        echo "artifact_registry_url=${artifact_registry_url}" >> "$GITHUB_OUTPUT"
        echo "static_bucket_name=${static_bucket_name}" >> "$GITHUB_OUTPUT"
        echo "load_balancer_ip=${load_balancer_ip}" >> "$GITHUB_OUTPUT"

        echo "Infra outputs:"
        echo "  Artifact Registry: ${artifact_registry_url}"
        echo "  Static Bucket: ${static_bucket_name}"
        echo "  Load Balancer IP: ${load_balancer_ip}"

    - name: Terraform Init (services layer)
      shell: bash
      working-directory: infrastructure/terraform/environments/${{ inputs.environment }}/services
      env:
        TF_STATE_BUCKET: ${{ inputs.terraform_state_bucket }}
        ENVIRONMENT: ${{ inputs.environment }}
      run: |
        terraform init -input=false \
          -backend-config="bucket=${TF_STATE_BUCKET}" \
          -backend-config="prefix=nopo/${ENVIRONMENT}/services"

    - name: Terraform Plan
      shell: bash
      working-directory: infrastructure/terraform/environments/${{ inputs.environment }}/services
      env:
        TF_VAR_project_id: ${{ inputs.project_id }}
        TF_VAR_region: ${{ inputs.region }}
        TF_VAR_domain: ${{ inputs.domain }}
        TF_VAR_terraform_state_bucket: ${{ inputs.terraform_state_bucket }}
      run: |
        echo "=== Terraform Plan (Services Layer) ==="
        
        # Always set all image variables as environment variables
        # If empty, set to empty string - Terraform will use the null default
        # We need to export them so they're available to terraform
        if [[ -n "${{ inputs.stable_backend_image }}" ]]; then
          export TF_VAR_stable_backend_image="${{ inputs.stable_backend_image }}"
          echo "  Stable Backend: ${{ inputs.stable_backend_image }}"
        else
          # Don't set the variable - let Terraform use the null default
          echo "  Stable Backend: <not deploying> (using default null)"
        fi
        
        if [[ -n "${{ inputs.stable_web_image }}" ]]; then
          export TF_VAR_stable_web_image="${{ inputs.stable_web_image }}"
          echo "  Stable Web: ${{ inputs.stable_web_image }}"
        else
          echo "  Stable Web: <not deploying> (using default null)"
        fi
        
        if [[ -n "${{ inputs.canary_backend_image }}" ]]; then
          export TF_VAR_canary_backend_image="${{ inputs.canary_backend_image }}"
          echo "  Canary Backend: ${{ inputs.canary_backend_image }}"
        else
          echo "  Canary Backend: <not deploying> (using default null)"
        fi
        
        if [[ -n "${{ inputs.canary_web_image }}" ]]; then
          export TF_VAR_canary_web_image="${{ inputs.canary_web_image }}"
          echo "  Canary Web: ${{ inputs.canary_web_image }}"
        else
          echo "  Canary Web: <not deploying> (using default null)"
        fi

        terraform plan -input=false -out=tfplan

    - name: Terraform Apply
      id: apply
      shell: bash
      working-directory: infrastructure/terraform/environments/${{ inputs.environment }}/services
      run: |
        # Plan file already contains only the targeted resources
        terraform apply -input=false -auto-approve tfplan

        # Extract outputs
        public_url=$(terraform output -raw public_url 2>/dev/null || echo "")
        canary_header=$(terraform output -raw canary_header 2>/dev/null || echo "")

        echo "public_url=${public_url}" >> "$GITHUB_OUTPUT"
        echo "canary_header=${canary_header}" >> "$GITHUB_OUTPUT"

        echo "=== Deploy Complete ==="
        echo "Public URL: ${public_url}"
        echo "Canary Header: ${canary_header}"

    - name: Cleanup plan file
      shell: bash
      working-directory: infrastructure/terraform/environments/${{ inputs.environment }}/services
      if: always()
      run: rm -f tfplan
