name: 'Claude Test Runner'
description: 'Intelligent E2E test runner with state prediction, exponential backoff polling, and self-healing diagnostics'

inputs:
  action:
    description: 'Action to perform: run | diagnose | wait | wait-triage | wait-phase | status | validate | run-configurable | run-discussion'
    required: true
  fixture_json:
    description: 'Test fixture JSON configuration'
    required: false
  issue_number:
    description: 'Issue number to test'
    required: false
  github_token:
    description: 'GitHub token with repo and project access'
    required: true
  project_number:
    description: 'GitHub Project number'
    required: false
    default: '1'
  target_status:
    description: 'Target status to wait for (for wait action)'
    required: false
  timeout:
    description: 'Timeout in seconds (default: 300 for triage, 900 for phase)'
    required: false
    default: '300'
  poll_interval:
    description: 'Poll interval in seconds (default: 10 for triage, 15 for phase)'
    required: false
    default: '10'
  phase_number:
    description: 'Phase number to wait for (for wait-phase action, 1-indexed)'
    required: false
    default: '1'
  cleanup_on_failure:
    description: 'Whether to trigger cleanup on test failure'
    required: false
    default: 'false'
  e2e_run_id:
    description: 'E2E test workflow run ID (enables e2e mode - adds config file to branch)'
    required: false
  # Configurable test runner inputs
  scenario_name:
    description: 'Name of the scenario to run (for run-configurable action)'
    required: false
  continue:
    description: 'Run to completion (true) or stop after one step (false)'
    required: false
    default: 'true'
  mock_claude:
    description: 'Mock Claude outputs from fixture files'
    required: false
    default: 'true'
  mock_ci:
    description: 'Mock CI (immediate pass/fail based on fixture)'
    required: false
    default: 'true'
  start_step:
    description: 'Start at a specific state (e.g., "iteratingFix")'
    required: false
  multi_issue:
    description: 'Create multiple sub-issues (true) or single issue (false)'
    required: false
    default: 'true'

outputs:
  status:
    description: 'Result status: done | timeout | error | completed | paused | failed'
  issue_number:
    description: 'Issue number used in the test'
  suggested_fix:
    description: 'Actionable fix suggestion if test failed'
  diagnosis:
    description: 'Detailed failure analysis'
  phases_completed:
    description: 'Number of phases completed successfully'
  total_duration_ms:
    description: 'Total test duration in milliseconds'
  # Additional outputs for status action
  iteration:
    description: 'Current iteration count'
  failures:
    description: 'Current failure count'
  bot_assigned:
    description: 'Whether nopo-bot is assigned'
  pr_number:
    description: 'PR number if exists'
  pr_state:
    description: 'PR state if exists'
  branch_exists:
    description: 'Whether the issue branch exists'
  unchecked_todos:
    description: 'Number of unchecked todos'
  predicted_state:
    description: 'Predicted next state'
  predicted_status:
    description: 'Predicted next status'
  workflow_status:
    description: 'Latest workflow run status'
  # Validate action outputs
  valid:
    description: 'Whether fixture is valid (for validate action)'
  errors:
    description: 'Validation errors (for validate action)'
  warnings:
    description: 'Validation warnings (for validate action)'
  # Wait-triage action outputs
  success:
    description: 'Whether the action succeeded (for wait-triage, wait-phase)'
  labels:
    description: 'JSON array of labels on the issue (for wait-triage)'
  project_fields:
    description: 'JSON object of project fields (for wait-triage)'
  sub_issue_count:
    description: 'Number of sub-issues created (for wait-triage)'
  # Wait-phase action outputs
  branch_name:
    description: 'Name of the created branch (for wait-phase)'
  ci_status:
    description: 'CI check status: pending | success | failure (for wait-phase)'
  review_status:
    description: 'Review status: pending | approved | changes_requested (for wait-phase)'
  issue_state:
    description: 'Issue state: open | closed (for wait-phase)'
  issue_status:
    description: 'Project status of the issue (for wait-phase)'
  # Configurable test runner outputs
  transitions:
    description: 'JSON array of state transitions executed (for run-configurable)'
  current_state:
    description: 'Current state if paused (for run-configurable)'
  next_state:
    description: 'Next state if paused (for run-configurable)'
  error:
    description: 'Error message if failed (for run-configurable)'
  # Discussion test runner outputs
  discussion_number:
    description: 'Discussion number created for the test (for run-discussion)'
  final_state:
    description: 'Final state after machine execution (for run-discussion)'
  actions_executed:
    description: 'Number of actions executed (for run-discussion)'
  verification_errors:
    description: 'Verification errors if any (for run-discussion)'

runs:
  using: node20
  main: dist/index.cjs
