name: Setup GCP
description: Authenticate with Google Cloud Platform and configure Docker

inputs:
  workload_identity_provider:
    description: The Workload Identity Provider
    required: true
  service_account:
    description: The Service Account email
    required: true
  project_id:
    description: The GCP project ID
    required: true
  region:
    description: The GCP region
    required: false
    default: "us-central1"

outputs:
  project_id:
    description: The GCP project ID
    value: ${{ inputs.project_id }}
  region:
    description: The GCP region
    value: ${{ inputs.region }}
  artifact_registry:
    description: The Artifact Registry URL
    value: ${{ inputs.region }}-docker.pkg.dev

runs:
  using: "composite"
  steps:
    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ inputs.workload_identity_provider }}
        service_account: ${{ inputs.service_account }}
        token_format: "access_token"

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ inputs.project_id }}

    - name: Configure Docker for Artifact Registry
      shell: bash
      env:
        REGION: ${{ inputs.region }}
      run: |
        gcloud auth configure-docker "${REGION}-docker.pkg.dev" --quiet
