name: Claude State Executor
description: Execute an array of actions derived from the state machine

inputs:
  github_code_token:
    description: GitHub PAT for code operations (nopo-bot) - push, PR, project fields
    required: true
  github_review_token:
    description: GitHub PAT for review operations (claude-reviewer) - submit reviews
    required: true
  actions_json:
    description: JSON array of actions to execute
    required: true
  project_number:
    description: GitHub Project number for state storage
    required: true
  # Status signaling inputs
  job:
    description: Job name for status comments (e.g., 'issue-iterate', 'pr-review')
    required: false
    default: ""
  resource_type:
    description: Resource type for status comments ('issue' or 'pr')
    required: false
    default: "issue"
  resource_number:
    description: Resource number (issue or PR number) for status comments
    required: false
    default: "0"
  comment_id:
    description: Comment ID that triggered this run (for reactions)
    required: false
    default: ""
  run_url:
    description: URL to the workflow run
    required: false
    default: ""
  dry_run:
    description: If true, log actions without executing
    required: false
    default: "false"

outputs:
  success:
    description: Whether all actions completed successfully
  stopped_early:
    description: Whether execution stopped before completing all actions
  stop_reason:
    description: Reason for stopping early (if applicable)
  actions_executed:
    description: Number of actions executed
  actions_failed:
    description: Number of actions that failed
  actions_skipped:
    description: Number of actions skipped (dry run)
  total_duration_ms:
    description: Total execution time in milliseconds
  results_json:
    description: JSON array of action results

runs:
  using: node20
  main: dist/index.cjs
