name: Deploy
description: Deploy a specific fly app

inputs:
  token:
    description: The Fly API token
    required: true
  version:
    description: The version to deploy
    required: false
  file:
    description: The file to deploy
    required: false
  app_name:
    description: The fly app name to deploy
    required: true

runs:
  using: 'composite'
  steps:
    - name: Deploy to Fly
      shell: bash
      env:
        FLY_API_TOKEN: ${{ inputs.token }}
        app_name: ${{ inputs.app_name }}
        version: ${{ inputs.version }}
        file: ${{ inputs.file }}
      run: make fly deploy app="${app_name}" version="${version}" file="${file}"


