name: Sub-Issue
description: A phase of work for a parent issue
title: "[Phase N]: "
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Sub-issues are typically created automatically during triage. Link to a parent issue using the sub-issues panel.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What should this phase accomplish?
      placeholder: |
        Describe the specific work for this phase.
        Include acceptance criteria if known.
    validations:
      required: true
