name: Issue
description: Create a new issue for Claude automation
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Describe what needs to be done. After creation, assign **nopo-bot** to trigger triage and implementation.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What needs to be done?
      placeholder: |
        Describe the problem, feature, or task.
        Include any relevant context, constraints, or requirements.
    validations:
      required: true
