name: Service Names
description: Discover service names from the apps directory

inputs:
  filter:
    description: Filter expression passed to nopo list (e.g., "buildable", "changed", "!image")
    required: false
    default: ""
  since:
    description: Git ref to compare against for "changed" filter (defaults to default branch)
    required: false
    default: ""

outputs:
  services:
    description: JSON array of service names
    value: ${{ steps.discover.outputs.services }}
  services_csv:
    description: Comma-separated list of service names
    value: ${{ steps.discover.outputs.services_csv }}
  count:
    description: Number of services discovered
    value: ${{ steps.discover.outputs.count }}

runs:
  using: "composite"
  steps:
    - name: Discover services
      id: discover
      shell: bash
      env:
        FILTER: ${{ inputs.filter }}
        SINCE: ${{ inputs.since }}
      run: |
        # Use nopo list to discover services
        # Assumes nopo CLI is available (setup-node action should be run before this)
        #
        # Examples:
        #   filter: ""          -> all services
        #   filter: "buildable" -> services with Dockerfiles
        #   filter: "changed"   -> services with changed files
        #   filter: "image"     -> services with pre-built images

        # Build the command arguments
        args="--json"
        if [[ -n "${FILTER}" ]]; then
          args="${args} --filter ${FILTER}"
        fi
        if [[ -n "${SINCE}" ]]; then
          args="${args} --since ${SINCE}"
        fi

        full_json=$(make list -- ${args})
        services_csv=$(make list -- ${args/--json/--csv})

        # Extract service names from JSON (avoiding pipe in make arguments)
        services_json=$(echo "${full_json}" | jq -c '.services | keys')
        count=$(echo "${services_json}" | jq 'length')

        echo "services=${services_json}" >> "$GITHUB_OUTPUT"
        echo "services_csv=${services_csv}" >> "$GITHUB_OUTPUT"
        echo "count=${count}" >> "$GITHUB_OUTPUT"

        echo "Discovered ${count} service(s): ${services_csv}"
