name: Service Names
description: Discover service names from the apps directory (services with Dockerfiles)

inputs:
  filter:
    description: Filter to specific service(s), comma-separated or "*" for all
    required: false
    default: "*"

outputs:
  services:
    description: JSON array of service names
    value: ${{ steps.discover.outputs.services }}
  services_csv:
    description: Comma-separated list of service names
    value: ${{ steps.discover.outputs.services_csv }}
  count:
    description: Number of services discovered
    value: ${{ steps.discover.outputs.count }}

runs:
  using: "composite"
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: "22"

    - name: Install nopo dependencies
      shell: bash
      run: |
        # Install only nopo scripts dependencies for fast discovery
        cd nopo/scripts && npm install --prefer-offline --no-audit --ignore-scripts 2>/dev/null || npm install

    - name: Discover services
      id: discover
      shell: bash
      env:
        FILTER: ${{ inputs.filter }}
      run: |
        # Use nopo list to discover services
        # This ensures consistency between CI and local development
        #
        # nopo list --json outputs: ["backend","web"]

        all_services_json=$(npx --yes tsx ./nopo/scripts/bin.ts list --json)
        
        echo "All services: ${all_services_json}"

        # Apply filter if not "*"
        if [[ "${FILTER}" == "*" ]]; then
          services_json="${all_services_json}"
        else
          # Convert comma-separated filter to array and filter JSON
          services_json=$(echo "${all_services_json}" | jq -c --arg filter "${FILTER}" '
            ($filter | split(",")) as $allowed |
            map(select(. as $s | $allowed | index($s)))
          ')
        fi

        # Convert to CSV
        services_csv=$(echo "${services_json}" | jq -r '. | join(",")')

        # Count services
        count=$(echo "${services_json}" | jq 'length')

        echo "services=${services_json}" >> "$GITHUB_OUTPUT"
        echo "services_csv=${services_csv}" >> "$GITHUB_OUTPUT"
        echo "count=${count}" >> "$GITHUB_OUTPUT"

        echo "Discovered ${count} service(s): ${services_csv}"
