name: Service Names
description: Discover service names from the apps directory (services with Dockerfiles)

inputs:
  apps_directory:
    description: The directory containing app subdirectories
    required: false
    default: "apps"
  filter:
    description: Filter to specific service(s), comma-separated or "*" for all
    required: false
    default: "*"

outputs:
  services:
    description: JSON array of service names
    value: ${{ steps.discover.outputs.services }}
  services_csv:
    description: Comma-separated list of service names
    value: ${{ steps.discover.outputs.services_csv }}
  count:
    description: Number of services discovered
    value: ${{ steps.discover.outputs.count }}

runs:
  using: "composite"
  steps:
    - name: Discover services
      id: discover
      shell: bash
      env:
        APPS_DIR: ${{ inputs.apps_directory }}
        FILTER: ${{ inputs.filter }}
      run: |
        # Discover services by finding directories in apps/ that contain a Dockerfile
        # This makes the service list dynamic based on the repository structure.
        #
        # Examples:
        #   apps/backend/Dockerfile -> "backend"
        #   apps/web/Dockerfile -> "web"
        #   apps/api/Dockerfile -> "api"
        #
        # Output: JSON array like ["backend","web"]

        if [[ ! -d "${APPS_DIR}" ]]; then
          echo "Error: Apps directory '${APPS_DIR}' not found"
          exit 1
        fi

        # Find all services (directories with Dockerfiles)
        all_services=$(
          find "${APPS_DIR}" -maxdepth 2 -name "Dockerfile" -type f \
            | xargs -n 1 dirname \
            | xargs -n 1 basename \
            | sort -u
        )

        # Apply filter if not "*"
        if [[ "${FILTER}" == "*" ]]; then
          filtered_services="${all_services}"
        else
          # Convert comma-separated filter to grep pattern
          pattern=$(echo "${FILTER}" | tr ',' '|')
          filtered_services=$(echo "${all_services}" | grep -E "^(${pattern})$" || true)
        fi

        # Convert to JSON array
        services_json=$(echo "${filtered_services}" | jq -R . | jq -s -c .)

        # Convert to CSV
        services_csv=$(echo "${filtered_services}" | tr '\n' ',' | sed 's/,$//')

        # Count services
        count=$(echo "${filtered_services}" | grep -c . || echo "0")

        echo "services=${services_json}" >> "$GITHUB_OUTPUT"
        echo "services_csv=${services_csv}" >> "$GITHUB_OUTPUT"
        echo "count=${count}" >> "$GITHUB_OUTPUT"

        echo "Discovered ${count} service(s): ${services_csv}"
        cat "$GITHUB_OUTPUT"
