name: Claude Signal Start
description: Signals that Claude is starting work (reactions and status comments)

inputs:
  github_token:
    description: GitHub token for API calls
    required: true
  resource_type:
    description: Type of resource (issue, pr, discussion)
    required: true
  resource_number:
    description: Issue/PR/Discussion number
    required: true
  comment_id:
    description: Comment ID to add reaction to (optional)
    required: false
  job:
    description: Job name being run (for status message)
    required: true

outputs:
  status_comment_id:
    description: ID of the status comment (for later update)

runs:
  using: node20
  main: dist/index.cjs
