name: Setup Docker
description: Setup Docker/Buildx

inputs:
  registry:
    description: The registry to use
    required: false
  username:
    description: The username to use
    required: false
  password:
    description: The password to use
    required: false
  driver:
    description: Buildx driver (docker = builtin, docker-container = full buildx)
    required: false
    default: docker

outputs:
  builder:
    description: 'Docker Buildx builder'
    value: ${{ steps.buildx.outputs.name }}

runs:
  using: composite
  steps:
    # QEMU only needed for multi-platform builds (docker-container driver)
    - name: Setup QEMU
      if: inputs.driver == 'docker-container'
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver: ${{ inputs.driver }}

    - name: Login Docker
      if: ${{ inputs.registry != '' && inputs.username != '' && inputs.password != '' }}
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
