// Machine
export { claudeMachine, getTriggerEvent } from "./machine.js";

// Guards
export {
  guards,
  // Individual guard exports for testing
  isAlreadyDone,
  isBlocked,
  isError,
  isTerminal,
  hasSubIssues,
  needsSubIssues,
  allPhasesDone,
  needsParentInit,
  currentPhaseComplete,
  hasNextPhase,
  subIssueNeedsAssignment,
  isInReview,
  currentPhaseNeedsWork,
  currentPhaseInReview,
  todosDone,
  hasPendingTodos,
  ciPassed,
  ciFailed,
  ciCancelled,
  maxFailuresReached,
  hasFailures,
  reviewApproved,
  reviewRequestedChanges,
  reviewCommented,
  hasPR,
  prIsDraft,
  prIsReady,
  prIsMerged,
  hasBranch,
  needsBranch,
  botIsAssigned,
  isFirstIteration,
  triggeredByAssignment,
  triggeredByEdit,
  triggeredByCI,
  triggeredByReview,
  triggeredByReviewRequest,
  triggeredByTriage,
  triggeredByComment,
  triggeredByOrchestrate,
  triggeredByPRReview,
  triggeredByPRResponse,
  triggeredByPRHumanResponse,
  triggeredByPRReviewApproved,
  triggeredByPRPush,
  triggeredByReset,
  triggeredByPivot,
  triggeredByMergeQueueEntry,
  triggeredByMergeQueueFailure,
  triggeredByPRMerged,
  triggeredByDeployedStage,
  triggeredByDeployedProd,
  needsTriage,
  isTriaged,
  triggeredByGroom,
  triggeredByGroomSummary,
  needsGrooming,
  isGroomed,
  needsInfo,
  readyForReview,
  shouldContinueIterating,
  shouldBlock,
} from "./guards.js";

// Actions
export {
  // Comment formatting
  formatCommentsForPrompt,
  // Status actions
  emitSetWorking,
  emitSetReview,
  emitSetInProgress,
  emitSetDone,
  emitSetBlocked,
  emitSetError,
  emitSetReady,
  emitLogInvalidIteration,
  // Iteration actions
  emitIncrementIteration,
  emitRecordFailure,
  emitClearFailures,
  // Issue actions
  emitCloseIssue,
  emitUnassign,
  emitResetIssue,
  // Branch actions
  emitCreateBranch,
  // PR actions
  emitCreatePR,
  emitMarkReady,
  emitConvertToDraft,
  emitRequestReview,
  emitMergePR,
  // Claude actions
  emitRunClaude,
  emitRunClaudeFixCI,
  emitRunClaudeTriage,
  emitRunClaudeComment,
  emitRunClaudePRReview,
  emitRunClaudePRResponse,
  emitRunClaudePRHumanResponse,
  emitRunClaudeGrooming,
  emitRunClaudePivot,
  // Orchestration actions
  emitAssignToSubIssue,
  emitInitializeParent,
  emitAdvancePhase,
  emitOrchestrate,
  emitAllPhasesDone,
  // Compound actions
  emitTransitionToReview,
  emitHandleCIFailure,
  emitBlockIssue,
  // Control flow actions
  emitStop,
  emitLog,
  // Merge queue logging actions
  emitMergeQueueEntry,
  emitMergeQueueFailure,
  emitMerged,
  emitDeployedStage,
  emitDeployedProd,
  // Push to draft action
  emitPushToDraft,
  // Label actions
  emitAddLabel,
  emitRemoveLabel,
  emitAddGroomedLabel,
  emitAddNeedsInfoLabel,
  emitRemoveNeedsInfoLabel,
} from "./actions.js";
