name: Claude Test Helper
description: Create, verify, and cleanup test fixtures for state machine testing

inputs:
  action:
    description: 'Action to perform: create, verify, cleanup, reset, close, delete, sweep, create_e2e_config, update_e2e_config'
    required: true
  fixture_json:
    description: 'JSON configuration for test scenario'
    required: false
  issue_number:
    description: 'Issue number (for verify/cleanup)'
    required: false
  github_token:
    description: 'GitHub token for code operations (issues, branches, PRs, project fields)'
    required: true
  github_review_token:
    description: 'GitHub token for review operations (must be different user than github_token)'
    required: false
    default: ''
  project_number:
    description: 'GitHub Project number for state storage'
    required: false
    default: '1'
  stepwise_mode:
    description: 'Whether to add _test label for stepwise testing mode'
    required: false
    default: 'false'
  dry_run_mode:
    description: 'Whether to skip test mode labels (just test:automation, workflows skip entirely)'
    required: false
    default: 'false'
  e2e_run_id:
    description: 'GitHub workflow run ID for e2e marker verification'
    required: false
    default: ''
  e2e_outcomes:
    description: 'JSON E2E outcomes config (overrides fixture e2e_outcomes)'
    required: false
    default: ''
  branch_name:
    description: 'Branch name for e2e config file operations (for create_e2e_config/update_e2e_config actions)'
    required: false
    default: ''
  iteration:
    description: 'Current iteration number for e2e config (for update_e2e_config action)'
    required: false
    default: '0'
  cleanup_mode:
    description: 'Cleanup mode: close (preserves history) or delete (permanent removal)'
    required: false
    default: 'close'
  manifest_dir:
    description: 'Directory containing manifest JSON files (for sweep action)'
    required: false
    default: ''

outputs:
  issue_number:
    description: 'Created parent issue number'
  sub_issue_numbers:
    description: 'Created sub-issue numbers (JSON array)'
  branch_name:
    description: 'Created branch name'
  pr_number:
    description: 'Created PR number'
  discussion_number:
    description: 'Created discussion number'
  comment_id:
    description: 'Created comment ID'
  verification_passed:
    description: 'Whether verification passed (true/false)'
  verification_errors:
    description: 'JSON array of verification errors'
  success:
    description: 'Whether cleanup/reset/close/delete succeeded'
  reset_count:
    description: 'Number of issues re-opened during reset'
  close_count:
    description: 'Number of issues closed during close action'
  delete_count:
    description: 'Number of issues deleted during delete action'
  config_path:
    description: 'Path to the e2e config file (for create_e2e_config/update_e2e_config actions)'

runs:
  using: node20
  main: dist/index.cjs
