name: Claude Handle Result
description: Handles job completion (update status comment, reactions, failure issue)

inputs:
  github_token:
    description: GitHub token for API calls
    required: true
  resource_type:
    description: Type of resource (issue, pr, discussion)
    required: true
  resource_number:
    description: Issue/PR/Discussion number
    required: true
  status_comment_id:
    description: ID of the status comment to update
    required: true
  comment_id:
    description: Comment ID to add reaction to (optional)
    required: false
  job:
    description: Job that was run
    required: true
  job_result:
    description: Result of the job (success, failure, cancelled, skipped)
    required: true
  run_url:
    description: URL to the workflow run
    required: true
  context_json:
    description: Context JSON for failure issue (optional)
    required: false

outputs:
  failure_issue_number:
    description: Issue number if a failure issue was created

runs:
  using: node20
  main: dist/index.cjs
