name: Run Claude
description: Load prompt and run Claude Code

inputs:
  # Prompt inputs (one of prompt or prompt_file is required)
  prompt:
    description: Direct prompt string (alternative to prompt_file)
    required: false
    default: ""
  prompt_file:
    description: Path to the prompt file (relative to repository root)
    required: false
    default: ""
  prompt_replacements:
    description: "JSON object of template replacements for prompt_file (e.g., '{\"ISSUE_NUMBER\": \"123\"}')"
    required: false
    default: "{}"

  # Required tokens
  github_token:
    description: GitHub token for API calls and Claude action
    required: true
  claude_code_oauth_token:
    description: OAuth token for Claude Code
    required: true

  # Claude configuration
  model:
    description: Claude model to use
    required: false
    default: "claude-opus-4-5-20251101"
  max_turns:
    description: Maximum number of API round-trips
    required: false
    default: "50"
  settings:
    description: Path to settings file
    required: false
    default: ".claude/settings.json"
  show_full_output:
    description: Whether to show full Claude output
    required: false
    default: "false"
  trigger_phrase:
    description: Trigger phrase for @-mentions (e.g., "@claude")
    required: false
    default: ""
  assignee_trigger:
    description: Assignee that triggers action (e.g., "nopo-bot")
    required: false
    default: ""

  # Mock mode configuration (for testing)
  mock_mode:
    description: Test mode - skip Claude API call and use mock responses
    required: false
    default: "false"
  mock_response:
    description: Mock response JSON to write to triage-output.json (used when mock_mode=true)
    required: false
    default: ""

outputs:
  success:
    description: Whether Claude completed successfully
    value: ${{ steps.result.outputs.success }}

runs:
  using: "composite"
  steps:
    # Step 1: Load and process prompt
    - name: Load prompt
      id: prompt
      shell: bash
      env:
        PROMPT: ${{ inputs.prompt }}
        PROMPT_FILE: ${{ inputs.prompt_file }}
        PROMPT_REPLACEMENTS: ${{ inputs.prompt_replacements }}
      run: |
        prompt=""

        # Use direct prompt if provided, otherwise load from file
        if [[ -n "$PROMPT" ]]; then
          prompt="$PROMPT"
        elif [[ -n "$PROMPT_FILE" ]]; then
          if [[ ! -f "$PROMPT_FILE" ]]; then
            echo "Error: Prompt file not found: $PROMPT_FILE"
            exit 1
          fi
          prompt=$(cat "$PROMPT_FILE")

          # Apply template replacements from JSON (only for file-based prompts)
          if [[ "$PROMPT_REPLACEMENTS" != "{}" ]]; then
            while IFS='=' read -r key value; do
              # Remove quotes from value if present
              value="${value%\"}"
              value="${value#\"}"
              # Replace {{KEY}} with value
              prompt="${prompt//\{\{$key\}\}/$value}"
            done < <(echo "$PROMPT_REPLACEMENTS" | jq -r 'to_entries[] | "\(.key)=\(.value)"')
          fi
        else
          echo "Error: Either prompt or prompt_file must be provided"
          exit 1
        fi

        # Save prompt to environment file for multiline content
        # Using heredoc delimiter for $GITHUB_OUTPUT
        {
          echo "prompt<<EOF_PROMPT_CONTENT"
          echo "$prompt"
          echo "EOF_PROMPT_CONTENT"
        } >> "$GITHUB_OUTPUT"

    # Step 2: Run Claude Code (or mock)
    - name: Run Claude (mock mode)
      id: claude_mock
      if: inputs.mock_mode == 'true' || inputs.mock_mode == true
      shell: bash
      env:
        MOCK_RESPONSE: ${{ inputs.mock_response }}
      run: |
        echo "Running in MOCK mode - skipping Claude API call"
        if [[ -n "$MOCK_RESPONSE" ]]; then
          echo "$MOCK_RESPONSE" > triage-output.json
          echo "Wrote mock response to triage-output.json"
          cat triage-output.json
        else
          echo "No mock response provided - creating default"
          echo '{"type":"enhancement","priority":"medium","size":"m","estimate":5,"topics":["test"],"needs_info":false}' > triage-output.json
        fi
        echo "Mock execution complete"

    - name: Run Claude (real mode)
      id: claude
      if: inputs.mock_mode != 'true' && inputs.mock_mode != true
      uses: anthropics/claude-code-action@v1
      with:
        claude_code_oauth_token: ${{ inputs.claude_code_oauth_token }}
        github_token: ${{ inputs.github_token }}
        prompt: ${{ steps.prompt.outputs.prompt }}
        settings: ${{ inputs.settings }}
        claude_args: "--model ${{ inputs.model }} --max-turns ${{ inputs.max_turns }}"
        show_full_output: ${{ inputs.show_full_output }}
        trigger_phrase: ${{ inputs.trigger_phrase }}
        assignee_trigger: ${{ inputs.assignee_trigger }}
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}

    # Step 3: Set result output
    - name: Set result
      id: result
      if: always()
      shell: bash
      run: |
        if [[ "${{ steps.claude.outcome }}" == "success" || "${{ steps.claude_mock.outcome }}" == "success" ]]; then
          echo "success=true" >> "$GITHUB_OUTPUT"
        else
          echo "success=false" >> "$GITHUB_OUTPUT"
        fi
