name: Claude Project State
description: Manages Claude automation state via GitHub Project fields

inputs:
  github_token:
    description: GitHub token for API calls (requires project read/write permissions)
    required: true
  issue_number:
    description: Issue number to read/update state from
    required: true
  action:
    description: |
      Action to perform:
      - read: Read project state (Status, Iteration, Failures)
      - update: Update project fields (Status, Iteration, Failures)
      - increment: Increment the Iteration counter
      - record_failure: Increment the Failures counter
      - clear_failures: Reset Failures to 0
      - append_history: Append entry to Iteration History in parent issue body
      - log_event: Alias for append_history (for backwards compatibility)
      - update_history: Update existing history entry matching pattern (e.g., update "Running..." to result)
      - get_current_phase: Get current phase from sub-issues
      - init_parent: Initialize parent issue with sub-issues
      - advance_phase: Advance to next phase after current is merged
      - set_blocked: Set issue status to Blocked (circuit breaker)
    required: true
  project_number:
    description: GitHub Project number (defaults to 1)
    required: false
    default: "1"
  status:
    description: Status value to set (for update action)
    required: false
  iteration:
    description: Iteration value to set (for update action)
    required: false
  failures:
    description: Failures value to set (for update action)
    required: false
  phase:
    description: Phase identifier for history entry (for append_history/update_history actions)
    required: false
  message:
    description: Message for history entry (for append_history/update_history actions)
    required: false
  iteration_message:
    description: Alias for message (backwards compatibility)
    required: false
  match_pattern:
    description: Pattern to match in existing history entry (for update_history action, defaults to "⏳")
    required: false
  commit_sha:
    description: Commit SHA for history entry
    required: false
  run_link:
    description: Workflow run link for history entry
    required: false
  parent_issue:
    description: Parent issue number (for get_current_phase, advance_phase)
    required: false
  sub_issues:
    description: Comma-separated list of sub-issue numbers (for init_parent)
    required: false
  completed_sub_issue:
    description: Sub-issue number that was completed (for advance_phase)
    required: false
  reason:
    description: Reason for blocking (for set_blocked action)
    required: false
  failure_type:
    description: Type of failure - ci or workflow (informational, for record_failure action)
    required: false

outputs:
  has_state:
    description: Whether state was found in project (true/false)
  status:
    description: Current status value from project
  iteration:
    description: Current iteration number
  failures:
    description: Current failures count
  consecutive_failures:
    description: Alias for failures (backwards compatibility)
  pr_number:
    description: PR number (if available, extracted from issue body)
  issue_body:
    description: Current issue body content
  issue_state:
    description: Issue state (open/closed)
  success:
    description: Whether the operation succeeded (true/false)
  updated:
    description: Whether an existing row was updated (for update_history, true/false)
  has_sub_issues:
    description: Whether parent has sub-issues (true/false)
  current_phase:
    description: Current phase number (1-indexed)
  current_sub_issue:
    description: Current sub-issue number
  current_phase_status:
    description: Status of current phase sub-issue
  current_phase_todos_done:
    description: Whether current phase todos are complete (true/false, parsed from issue body)
  current_phase_title:
    description: 'Title of current phase (from "## Phase N: Title" or "Todo" for single-phase)'
  total_phases:
    description: Total number of phases (sub-issues)
  all_phases_done:
    description: Whether all phases are complete (true/false)
  branch:
    description: Derived branch name for current phase
  sub_issues:
    description: Comma-separated list of sub-issue numbers
  next_phase:
    description: Next phase number (for advance_phase)
  next_sub_issue:
    description: Next sub-issue number (for advance_phase)

runs:
  using: node20
  main: dist/index.cjs
