# Generated by Django 5.2.3 on 2025-06-30 11:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TodoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the todo item",
                        max_length=200,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional detailed description", null=True
                    ),
                ),
                (
                    "completed",
                    models.BooleanField(
                        default=False, help_text="Whether this todo item is completed"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this todo item was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this todo item was last updated"
                    ),
                ),
                (
                    "due_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional due date for this todo item",
                        null=True,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        help_text="Priority level of this todo item",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["completed"], name="todo_todoit_complet_1db831_idx"
                    ),
                    models.Index(
                        fields=["priority"], name="todo_todoit_priorit_24b08a_idx"
                    ),
                    models.Index(
                        fields=["due_date"], name="todo_todoit_due_dat_2856c4_idx"
                    ),
                ],
            },
        ),
    ]
